openapi: 3.0.0
info:
  description: |
    Тестовое api для каталога автомобилей
  version: 1.0.0
  title: 'carcatalog'
servers:
  - url: http://api.carcatalog/index.php?cars
    description: 'Для работы с каталогом машин'
  - url: http://api.carcatalog/index.php?users
    description: 'Для работы с пользователями'
tags:
  - name: cars
    description: 'Все про машины'
  - name: users
    description: 'Все про пользователей'
paths:
  #http://api.carcatalog/api/index.php?cars
  /:
    get:
      tags:
        - cars
      summary: 'Выводит все машини в каталоге'
      operationId: getCars
      responses:
        '200':
          description: ''
  #api.carcatalog/api/index.php?cars/0
  /cars/{category_id}:
    post:
      tags:
        - cars
      operationId: addCars
      parameters:
        - in: path
          name: category_id
          schema:
            type: array
            items:
              type: integer
          description: 'Катеогория по которой проводится сортировка '
          required: true
      responses:
        '201':
          description: ''